### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by alex-bacart** [stimulus-components/stimulus-sound#1]
I've tried to install this component and have got an error:

```bash
Could not resolve dependency:
peer @hotwired/stimulus@"3.2.1" from stimulus-sound@1.0.0
```

package.json requires **exactly** 3.2.1 version of stimulus and my installed version 3.2.2 doesn't allow me to install it.

I took a look at another components and they require `^3.2.1` (3.2.1 or higher):
1. https://github.com/stimulus-components/stimulus-checkbox-select-all/blob/dce710708dc8a986f99da87c1d390abf7dcca211/package.json#L55
2. https://github.com/stimulus-components/stimulus-timeago/blob/778c1e70c75fdd465eeed225a3d6f939bb7bb714/package.json#L56

So I assume it's a typo in stimulus-sound component's package.json.

**Comment by guillaumebriday** [comment]
You can ignore the error but you're right, we need to update it 👍
